export const GET_ERROR ="GET_ERROR"

// Products
export const GET_ALL_PRODUCTS ="GET_ALL_PRODUCTS"

export const GET_ALL_TOP_SELLING ="GET_ALL_TOP_SELLING"

export const GET_ALL_PRODUCTS_FILTER ="GET_ALL_PRODUCTS_FILTER"

export const SINGLE_PRODUCT ="SINGLE_PRODUCT"

export const GET_ALL_ADMIN_PRODUCTS ="GET_ALL_ADMIN_PRODUCTS" 

export const CREATE_PRODUCT = "CREATE_PRODUCT" 

export const ADMIN_SIGLE_PRODUCT = "ADMIN_SIGLE_PRODUCT" 

export const UPDATE_PRODUCT = "UPDATE_PRODUCT" 

export const DELETE_PRODUCT = "DELETE_PRODUCT" 

export const SIMILAR_PRODUCTS = "SIMILAR_PRODUCTS" 


// Category
export const CREATE_CATEGORY = "CREATE_CATEGORY" 

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES" 

//  Sub Category
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY" 

export const GET_ALL_SUB_CATEGORIES = "GET_ALL_SUB_CATEGORIES" 




// Users 
export const CREATE_NEW_USER ="CREATE_NEW_USER"

export const GET_SINGLE_USER ="GET_SINGLE_USER"

export const GET_ALL_USERS ="GET_ALL_USERS"

export const UPDATE_USER_DATA ="UPDATE_USER_DATA"

export const BLOCK_USER ="BLOCK_USER"

export const UN_BLOCK_USER ="UN_BLOCK_USER"

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';


export const LOGIN_USER = 'LOGIN_USER';


export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';

export const GET_USER_DATA = 'GET_USER_DATA';

export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const SEARCH_USER = 'SEARCH_USER';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';

export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';

export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';

export const RESET_PASSWORD = 'RESET_PASSWORD';

export const CONTACT_MESSAGE = 'CONTACT_MESSAGE';

// Merchant Requests
export const CREATE_NEW_REQUEST = 'CREATE_NEW_REQUEST';

export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS';

export const UPDATE_USER_MERCHANT ="UPDATE_USER_MERCHANT"

export const DELETE_REQUEST = 'DELETE_REQUEST';



// Cart
export const ADD_TO_CART = "ADD_TO_CART";


export const GET_USER_CART = "GET_USER_CART";

export const DELTE_CART_ITEM = "DELTE_CART_ITEM";

export const UPDATE_ONE_PRODUCT_CART = "UPDATE_ONE_PRODUCT_CART";


// Orders 

export const CREATE_NEW_ORDER = "CREATE_NEW_ORDER"

export const GET_ALL_ADMIN_ORDERS = "GET_ALL_ADMIN_ORDERS"


export const GET_ALL_USERS_ORDERS = "GET_ALL_USERS_ORDERS" 

export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS" 


export const SINGLE_ORDER = "SINGLE_ORDER" 

export const VERIFY_COUPON = "VERIFY_COUPON" 

export const SEARCH_ORDER = "SEARCH_ORDER" 
//  Offer

export const CREATE_NEW_COUPON = "CREATE_NEW_COUPON"


export const CREATE_NEW_DISCOUNT = "CREATE_NEW_DISCOUNT"

export const GET_DISCOUNT = "GET_DISCOUNT"

export const GET_COUPON = "GET_COUPON"

export const DELETE_DISCOUNT = "DELETE_DISCOUNT"

export const DELETE_COUPON = "DELETE_COUPON"

export const UPDATE_COUPON = "UPDATE_COUPON"

export const UPDATE_DISCOUNT = "UPDATE_DISCOUNT"

export const GET_SINGLE_COUPON = "GET_SINGLE_COUPON"

export const GET_SINGLE_DISCOUNT = "GET_SINGLE_DISCOUNT"


// Analytics

export const GET_ANALYTICS = "GET_ANALYTICS"
